### PR TITLE
Update rf-links-list.md

### PR DESCRIPTION
**Pull request by Russell-KV4S**
Added RF LInk: 15019

### CODE REVIEW

**Comment by n8acl** [comment]
It needs to be an email address, not a website link in the contact information. If you add that, I can merge it.

**Comment by n8acl** [comment]
Sorry hit the wrong button.. didn't mean to close it without letting you change it...

**Comment by n8acl** [comment]
That works....

**Comment by Russell-KV4S** [comment]
Awesome, thanks! 
Enjoying the system!

**Comment by n8acl** [comment]
Yeppers no problem.. thanks for adding that :)

**Pull request merged**
